assistant_name: assistant
prompt: default
model_api: openai_chat
model_name: gpt-3.5-turbo
model_args:
  temperature: 0
knowledge: default
memory: default
conversation_dir: ./conversations
environment_variables:
  - .env
